### ISSUE TITLE
Change from http to https

### ISSUE THREAD

**Issue by Jacalz** [zynaddsubfx/zyn-website#3]
Http is considered insecure and it's becoming standard precipices to use https everywhere possible.

**Comment by fundamental** [comment]
To the best of my knowledge this is not something which can be controlled for the project website for projects using sourceforge.

**Comment by Jacalz** [comment]
I am pretty sure that it is possible, take Qtractor as an example. The .io page is using https https://qtractor.sourceforge.io/ , but the .net site is using http (or was until recently because now it just forwards to the https site).
